import type { KeyDefinition } from './cdpTypes';

export const MAC_KEYBOARD_COMMANDS: Record<string, string | string[]> = {
  backspace: 'deleteBackward',
  enter: 'insertNewline',
  numpadenter: 'insertNewline',
  kp_enter: 'insertNewline',
  escape: 'cancelOperation',
  arrowup: 'moveUp',
  arrowdown: 'moveDown',
  arrowleft: 'moveLeft',
  arrowRight: 'moveRight',
  up: 'moveUp',
  down: 'moveDown',
  left: 'moveLeft',
  right: 'moveRight',
  f5: 'complete',
  delete: 'deleteForward',
  home: 'scrollToBeginningOfDocument',
  end: 'scrollToEndOfDocument',
  pageup: 'scrollPageUp',
  pagedown: 'scrollPageDown',
  'shift+backspace': 'deleteBackward',
  'shift+enter': 'insertNewline',
  'shift+escape': 'cancelOperation',
  'shift+arrowup': 'moveUpAndModifySelection',
  'shift+arrowdown': 'moveDownAndModifySelection',
  'shift+arrowleft': 'moveLeftAndModifySelection',
  'shift+arrowright': 'moveRightAndModifySelection',
  'shift+up': 'moveUpAndModifySelection',
  'shift+down': 'moveDownAndModifySelection',
  'shift+left': 'moveLeftAndModifySelection',
  'shift+right': 'moveRightAndModifySelection',
  'shift+f5': 'complete',
  'shift+delete': 'deleteForward',
  'shift+home': 'moveToBeginningOfDocumentAndModifySelection',
  'shift+end': 'moveToEndOfDocumentAndModifySelection',
  'shift+pageup': 'pageUpAndModifySelection',
  'shift+pagedown': 'pageDownAndModifySelection',
  'shift+numpad5': 'delete',
  'ctrl+tab': 'selectNextKeyView',
  'ctrl+enter': 'insertLineBreak',
  'ctrl+numpadenter': 'insertLineBreak',
  'ctrl+kp_enter': 'insertLineBreak',
  'ctrl+quote': 'insertSingleQuoteIgnoringSubstitution',
  "ctrl+'": 'insertSingleQuoteIgnoringSubstitution',
  'ctrl+a': 'moveToBeginningOfParagraph',
  'ctrl+b': 'moveBackward',
  'ctrl+d': 'deleteForward',
  'ctrl+e': 'moveToEndOfParagraph',
  'ctrl+f': 'moveForward',
  'ctrl+h': 'deleteBackward',
  'ctrl+k': 'deleteToEndOfParagraph',
  'ctrl+l': 'centerSelectionInVisibleArea',
  'ctrl+n': 'moveDown',
  'ctrl+p': 'moveUp',
  'ctrl+t': 'transpose',
  'ctrl+v': 'moveUp',
  'ctrl+y': 'yank',
  'ctrl+o': ['insertNewlineIgnoringFieldEditor', 'moveBackward'],
  'ctrl+backspace': 'deleteBackwardByDecomposingPreviousCharacter',
  'ctrl+arrowup': 'scrollPageUp',
  'ctrl+arrowdown': 'scrollPageDown',
  'ctrl+arrowleft': 'moveToLeftEndOfLine',
  'ctrl+arrowright': 'moveToRightEndOfLine',
  'ctrl+up': 'scrollPageUp',
  'ctrl+down': 'scrollPageDown',
  'ctrl+left': 'moveToLeftEndOfLine',
  'ctrl+right': 'moveToRightEndOfLine',
  'shift+ctrl+enter': 'insertLineBreak',
  'shift+control+numpadenter': 'insertLineBreak',
  'shift+control+kp_enter': 'insertLineBreak',
  'shift+ctrl+tab': 'selectPreviousKeyView',
  'shift+ctrl+quote': 'insertDoubleQuoteIgnoringSubstitution',
  "shift+ctrl+'": 'insertDoubleQuoteIgnoringSubstitution',
  'ctrl+"': 'insertDoubleQuoteIgnoringSubstitution',
  'shift+ctrl+a': 'moveToBeginningOfParagraphAndModifySelection',
  'shift+ctrl+b': 'moveBackwardAndModifySelection',
  'shift+ctrl+e': 'moveToEndOfParagraphAndModifySelection',
  'shift+ctrl+f': 'moveForwardAndModifySelection',
  'shift+ctrl+n': 'moveDownAndModifySelection',
  'shift+ctrl+p': 'moveUpAndModifySelection',
  'shift+ctrl+v': 'pageDownAndModifySelection',
  'shift+ctrl+backspace': 'deleteBackwardByDecomposingPreviousCharacter',
  'shift+ctrl+arrowup': 'scrollPageUp',
  'shift+ctrl+arrowdown': 'scrollPageDown',
  'shift+ctrl+arrowleft': 'moveToLeftEndOfLineAndModifySelection',
  'shift+ctrl+arrowright': 'moveToRightEndOfLineAndModifySelection',
  'shift+ctrl+up': 'scrollPageUp',
  'shift+ctrl+down': 'scrollPageDown',
  'shift+ctrl+left': 'moveToLeftEndOfLineAndModifySelection',
  'shift+ctrl+right': 'moveToRightEndOfLineAndModifySelection',
  'alt+backspace': 'deleteWordBackward',
  'alt+enter': 'insertNewlineIgnoringFieldEditor',
  'alt+numpadenter': 'insertNewlineIgnoringFieldEditor',
  'alt+kp_enter': 'insertNewlineIgnoringFieldEditor',
  'alt+escape': 'complete',
  'alt+arrowup': ['moveBackward', 'moveToBeginningOfParagraph'],
  'alt+arrowdown': ['moveForward', 'moveToEndOfParagraph'],
  'alt+arrowleft': 'moveWordLeft',
  'alt+arrowright': 'moveWordRight',
  'alt+up': ['moveBackward', 'moveToBeginningOfParagraph'],
  'alt+down': ['moveForward', 'moveToEndOfParagraph'],
  'alt+left': 'moveWordLeft',
  'alt+right': 'moveWordRight',
  'alt+delete': 'deleteWordForward',
  'alt+pageup': 'pageUp',
  'alt+pagedown': 'pageDown',
  'shift+alt+backspace': 'deleteWordBackward',
  'shift+alt+enter': 'insertNewlineIgnoringFieldEditor',
  'shift+alt+numpadenter': 'insertNewlineIgnoringFieldEditor',
  'shift+alt+kp_enter': 'insertNewlineIgnoringFieldEditor',
  'shift+alt+escape': 'complete',
  'shift+alt+arrowup': 'moveParagraphBackwardAndModifySelection',
  'shift+alt+arrowdown': 'moveParagraphForwardAndModifySelection',
  'shift+alt+arrowleft': 'moveWordLeftAndModifySelection',
  'shift+alt+arrowright': 'moveWordRightAndModifySelection',
  'shift+alt+up': 'moveParagraphBackwardAndModifySelection',
  'shift+alt+down': 'moveParagraphForwardAndModifySelection',
  'shift+alt+left': 'moveWordLeftAndModifySelection',
  'shift+alt+right': 'moveWordRightAndModifySelection',
  'shift+alt+delete': 'deleteWordForward',
  'shift+alt+pageup': 'pageUp',
  'shift+alt+pagedown': 'pageDown',
  'ctrl+alt+b': 'moveWordBackward',
  'ctrl+alt+f': 'moveWordForward',
  'ctrl+alt+backspace': 'deleteWordBackward',
  'shift+ctrl+alt+b': 'moveWordBackwardAndModifySelection',
  'shift+ctrl+alt+f': 'moveWordForwardAndModifySelection',
  'shift+ctrl+alt+backspace': 'deleteWordBackward',
  'cmd+numpadsubtract': 'cancel',
  'cmd+backspace': 'deleteToBeginningOfLine',
  'cmd+arrowup': 'moveToBeginningOfDocument',
  'cmd+arrowdown': 'moveToEndOfDocument',
  'cmd+arrowleft': 'moveToLeftEndOfLine',
  'cmd+arrowright': 'moveToRightEndOfLine',
  'cmd+home': 'moveToBeginningOfDocument',
  'cmd+up': 'moveToBeginningOfDocument',
  'cmd+down': 'moveToEndOfDocument',
  'cmd+left': 'moveToLeftEndOfLine',
  'cmd+right': 'moveToRightEndOfLine',
  'shift+cmd+numpadsubtract': 'cancel',
  'shift+cmd+backspace': 'deleteToBeginningOfLine',
  'shift+cmd+arrowup': 'moveToBeginningOfDocumentAndModifySelection',
  'shift+cmd+arrowdown': 'moveToEndOfDocumentAndModifySelection',
  'shift+cmd+arrowleft': 'moveToLeftEndOfLineAndModifySelection',
  'shift+cmd+arrowright': 'moveToRightEndOfLineAndModifySelection',
  'cmd+a': 'selectAll',
  'cmd+c': 'copy',
  'cmd+x': 'cut',
  'cmd+v': 'paste',
  'cmd+z': 'undo',
  'shift+cmd+z': 'redo'
};

export const KEY_DEFINITIONS: Record<string, KeyDefinition> = {
  enter: { key: 'Enter', code: 'Enter', keyCode: 13, text: '\r' },
  return: { key: 'Enter', code: 'Enter', keyCode: 13, text: '\r' },
  kp_enter: { key: 'Enter', code: 'Enter', keyCode: 13, text: '\r', isKeypad: true },
  tab: { key: 'Tab', code: 'Tab', keyCode: 9 },
  delete: { key: 'Delete', code: 'Delete', keyCode: 46 },
  backspace: { key: 'Backspace', code: 'Backspace', keyCode: 8 },
  escape: { key: 'Escape', code: 'Escape', keyCode: 27 },
  esc: { key: 'Escape', code: 'Escape', keyCode: 27 },
  space: { key: ' ', code: 'Space', keyCode: 32, text: ' ' },
  ' ': { key: ' ', code: 'Space', keyCode: 32, text: ' ' },
  arrowup: { key: 'ArrowUp', code: 'ArrowUp', keyCode: 38 },
  arrowdown: { key: 'ArrowDown', code: 'ArrowDown', keyCode: 40 },
  arrowleft: { key: 'ArrowLeft', code: 'ArrowLeft', keyCode: 37 },
  arrowright: { key: 'ArrowRight', code: 'ArrowRight', keyCode: 39 },
  up: { key: 'ArrowUp', code: 'ArrowUp', keyCode: 38 },
  down: { key: 'ArrowDown', code: 'ArrowDown', keyCode: 40 },
  left: { key: 'ArrowLeft', code: 'ArrowLeft', keyCode: 37 },
  right: { key: 'ArrowRight', code: 'ArrowRight', keyCode: 39 },
  home: { key: 'Home', code: 'Home', keyCode: 36 },
  end: { key: 'End', code: 'End', keyCode: 35 },
  pageup: { key: 'PageUp', code: 'PageUp', keyCode: 33 },
  pagedown: { key: 'PageDown', code: 'PageDown', keyCode: 34 },
  f1: { key: 'F1', code: 'F1', keyCode: 112 },
  f2: { key: 'F2', code: 'F2', keyCode: 113 },
  f3: { key: 'F3', code: 'F3', keyCode: 114 },
  f4: { key: 'F4', code: 'F4', keyCode: 115 },
  f5: { key: 'F5', code: 'F5', keyCode: 116 },
  f6: { key: 'F6', code: 'F6', keyCode: 117 },
  f7: { key: 'F7', code: 'F7', keyCode: 118 },
  f8: { key: 'F8', code: 'F8', keyCode: 119 },
  f9: { key: 'F9', code: 'F9', keyCode: 120 },
  f10: { key: 'F10', code: 'F10', keyCode: 121 },
  f11: { key: 'F11', code: 'F11', keyCode: 122 },
  f12: { key: 'F12', code: 'F12', keyCode: 123 },
  ';': { key: ';', code: 'Semicolon', keyCode: 186, text: ';' },
  '=': { key: '=', code: 'Equal', keyCode: 187, text: '=' },
  ',': { key: ',', code: 'Comma', keyCode: 188, text: ',' },
  '-': { key: '-', code: 'Minus', keyCode: 189, text: '-' },
  '.': { key: '.', code: 'Period', keyCode: 190, text: '.' },
  '/': { key: '/', code: 'Slash', keyCode: 191, text: '/' },
  '`': { key: '`', code: 'Backquote', keyCode: 192, text: '`' },
  '[': { key: '[', code: 'BracketLeft', keyCode: 219, text: '[' },
  '\\': { key: '\\', code: 'Backslash', keyCode: 220, text: '\\' },
  ']': { key: ']', code: 'BracketRight', keyCode: 221, text: ']' },
  "'": { key: "'", code: 'Quote', keyCode: 222, text: "'" },
  '!': { key: '!', code: 'Digit1', keyCode: 49, text: '!' },
  '@': { key: '@', code: 'Digit2', keyCode: 50, text: '@' },
  '#': { key: '#', code: 'Digit3', keyCode: 51, text: '#' },
  $: { key: '$', code: 'Digit4', keyCode: 52, text: '$' },
  '%': { key: '%', code: 'Digit5', keyCode: 53, text: '%' },
  '^': { key: '^', code: 'Digit6', keyCode: 54, text: '^' },
  '&': { key: '&', code: 'Digit7', keyCode: 55, text: '&' },
  '*': { key: '*', code: 'Digit8', keyCode: 56, text: '*' },
  '(': { key: '(', code: 'Digit9', keyCode: 57, text: '(' },
  ')': { key: ')', code: 'Digit0', keyCode: 48, text: ')' },
  _: { key: '_', code: 'Minus', keyCode: 189, text: '_' },
  '+': { key: '+', code: 'Equal', keyCode: 187, text: '+' },
  '{': { key: '{', code: 'BracketLeft', keyCode: 219, text: '{' },
  '}': { key: '}', code: 'BracketRight', keyCode: 221, text: '}' },
  '|': { key: '|', code: 'Backslash', keyCode: 220, text: '|' },
  ':': { key: ':', code: 'Semicolon', keyCode: 186, text: ':' },
  '"': { key: '"', code: 'Quote', keyCode: 222, text: '"' },
  '<': { key: '<', code: 'Comma', keyCode: 188, text: '<' },
  '>': { key: '>', code: 'Period', keyCode: 190, text: '>' },
  '?': { key: '?', code: 'Slash', keyCode: 191, text: '?' },
  '~': { key: '~', code: 'Backquote', keyCode: 192, text: '~' },
  capslock: { key: 'CapsLock', code: 'CapsLock', keyCode: 20 },
  numlock: { key: 'NumLock', code: 'NumLock', keyCode: 144 },
  scrolllock: { key: 'ScrollLock', code: 'ScrollLock', keyCode: 145 },
  pause: { key: 'Pause', code: 'Pause', keyCode: 19 },
  insert: { key: 'Insert', code: 'Insert', keyCode: 45 },
  printscreen: { key: 'PrintScreen', code: 'PrintScreen', keyCode: 44 },
  numpad0: { key: '0', code: 'Numpad0', keyCode: 96, isKeypad: true },
  numpad1: { key: '1', code: 'Numpad1', keyCode: 97, isKeypad: true },
  numpad2: { key: '2', code: 'Numpad2', keyCode: 98, isKeypad: true },
  numpad3: { key: '3', code: 'Numpad3', keyCode: 99, isKeypad: true },
  numpad4: { key: '4', code: 'Numpad4', keyCode: 100, isKeypad: true },
  numpad5: { key: '5', code: 'Numpad5', keyCode: 101, isKeypad: true },
  numpad6: { key: '6', code: 'Numpad6', keyCode: 102, isKeypad: true },
  numpad7: { key: '7', code: 'Numpad7', keyCode: 103, isKeypad: true },
  numpad8: { key: '8', code: 'Numpad8', keyCode: 104, isKeypad: true },
  numpad9: { key: '9', code: 'Numpad9', keyCode: 105, isKeypad: true },
  numpadmultiply: { key: '*', code: 'NumpadMultiply', keyCode: 106, isKeypad: true },
  numpadadd: { key: '+', code: 'NumpadAdd', keyCode: 107, isKeypad: true },
  numpadsubtract: { key: '-', code: 'NumpadSubtract', keyCode: 109, isKeypad: true },
  numpaddecimal: { key: '.', code: 'NumpadDecimal', keyCode: 110, isKeypad: true },
  numpaddivide: { key: '/', code: 'NumpadDivide', keyCode: 111, isKeypad: true }
};
